/**
 * Markdown rendered into the OpenAPI `info.description` block. Kept here so
 * server.ts stays small and so the docs source diffs cleanly.
 */
export const apiDescription = [
  "API-first HR service for [1tap.ai](https://1tap.ai). One master integrator (1tap) provisions and operates many startup tenants. End users never log in to MyHR — 1tap brings their own UI and OAuth and calls this API on their behalf.",
  "",
  "## Authentication",
  "",
  "All authenticated requests send a bearer token:",
  "",
  "```",
  "Authorization: Bearer <token>",
  "```",
  "",
  "Three credential types are accepted (each operation lists which subset it allows):",
  "",
  "| Scheme | Token format | Used by |",
  "| --- | --- | --- |",
  "| `masterApiKey` | `mh_live_…` (env `MASTER_API_KEY`) | 1tap's backend, cross-tenant |",
  "| `tenantApiKey` | `mh_live_…` (minted from dashboard) | A startup's own integrations |",
  "| `userSession` | Auth-service access token (JWT) | The MyHR web app, on behalf of a user |",
  "",
  "## Tenant scoping",
  "",
  "Tenant-scoped endpoints resolve the tenant org per caller type:",
  "",
  "- `masterApiKey` → `X-Tenant-Id` header (UUID).",
  "- `tenantApiKey` → derived from the key; the header is ignored.",
  "- `userSession` → `X-Org-Id` header, validated against the user's memberships.",
  "",
  "All data access is enforced by Postgres Row-Level Security — a missing or wrong tenant id never returns another tenant's data.",
  "",
  "## Audit attribution",
  "",
  "Master callers can pass `X-Actor: {\"id\":\"u_123\",\"email\":\"a@b\",\"name\":\"Ada\"}` (JSON) to attribute the request to a specific 1tap user in the audit log. User-session callers cannot set `X-Actor` (the actor is taken from the session to prevent spoofing).",
  "",
  "## Idempotency",
  "",
  "Writes (`POST` / `PATCH` / `DELETE`) require an `Idempotency-Key` header (any unique string per logical operation, typically a UUID). Replays within 24h return the cached response. Reusing a key with a different request body returns `409 conflict`.",
  "",
  "## Errors",
  "",
  "Every error response uses a single envelope:",
  "",
  "```json",
  "{ \"error\": { \"code\": \"not_found\", \"message\": \"...\", \"details\": {} } }",
  "```",
  "",
  "Stable codes: `bad_request`, `tenant_required`, `unauthorized`, `forbidden`, `not_found`, `conflict`, `internal_error`. New codes are additive — clients should switch on `code` and treat unknown codes as a generic failure.",
  "",
  "## Pagination",
  "",
  "List endpoints use opaque cursors. Pass `?limit=` (1–200, default 50) and `?cursor=<value>` to page forward. The response is `{ items: [...], nextCursor: string | null }` — `nextCursor: null` means you're at the end. Cursors are stable across writes (deletions skip rather than fail).",
  "",
  "## Rate limits",
  "",
  "Each `masterApiKey` and `tenantApiKey` is limited to **600 requests / minute**, burst 60/sec. Limits are returned on every response:",
  "",
  "- `RateLimit-Limit` — total per window",
  "- `RateLimit-Remaining` — left in window",
  "- `RateLimit-Reset` — seconds until reset",
  "",
  "Exceeding the limit returns `429 too_many_requests`. Retry with exponential backoff using the `Retry-After` header.",
  "",
  "## Versioning",
  "",
  "The major version is in the URL (`/v1`). Within a major version we only make additive changes (new fields, new operations, new error codes). Deprecations are announced at least 90 days in advance via the `Deprecation` and `Sunset` response headers ([RFC 8594](https://www.rfc-editor.org/rfc/rfc8594)) and called out in [`apps/api/CHANGELOG.md`](https://github.com/proark1/hr/blob/main/apps/api/CHANGELOG.md).",
  "",
  "Breaking changes only ever ship under a new major (`/v2`), and `/v1` will run alongside it for at least 12 months.",
  "",
  "## Webhooks",
  "",
  "Register a delivery URL via `POST /v1/webhook-endpoints` with the events you want — currently `employee.created`, `employee.updated`, `employee.deleted`, and (forthcoming) `document.expiring`. The signing secret is returned once at creation; use it to verify the `Webhook-Signature` header on every inbound delivery. The header value is `t=<unix-seconds>,v1=<hex-hmac-sha256>` of `<t>.<raw-body>`, the same format Stripe uses; the SDK exposes `verifyWebhookSignature()` for convenience.",
  "",
  "Delivery semantics: each event is enqueued per subscribed endpoint with up to 8 attempts and exponential backoff (~1s → ~17h). The delivery audit log is queryable at `/v1/webhook-deliveries`, and any non-`delivered` row can be re-enqueued via `/v1/webhook-deliveries/{id}/redeliver`. Receivers must respond with any 2xx within 10s; non-2xx triggers a retry.",
  "",
  "## Quickstart",
  "",
  "```bash",
  "curl https://api.myhr.example/v1/employees \\",
  "  -H 'Authorization: Bearer $MASTER_API_KEY' \\",
  "  -H 'X-Tenant-Id: 11111111-2222-3333-4444-555555555555' \\",
  "  -H 'Idempotency-Key: '\"$(uuidgen)\" \\",
  "  -H 'Content-Type: application/json' \\",
  "  -d '{\"email\":\"ada@acme.com\",\"firstName\":\"Ada\",\"lastName\":\"Lovelace\",\"country\":\"us\",\"startDate\":\"2026-06-01\"}'",
  "```",
].join("\n");
